---
title: "Reproducible Document"
author: "rostools"
format: html
---

Setup makes the chunk run as the first 

```{r}
download.file(
  url = "https://zenodo.org/records/4989220/files/Eliasson_data2.csv?download=1",
  destfile = here::here("data/post-meal-insulin.csv")
)
```

```{r}
```




```{r setup}
#| message: false
#| warning: false

library(tidyverse)

post_meal_data <- read_csv2(here::here("data/post-meal-insulin.csv"))
```

## About me

- Marie Aarup Storgaard
- Department of hepatology and gastroenterologi, Aarhus University Hospital

*I* am a **PhD student**

## Simpel code

```{r}
3*3
```



## Writing R code

2+2


```{r}
head(airquality)
```

```{r}
weight_kilos <- 100
weight_kilos
```



```{r}
character <- c("a", "b", "c")
logic <- c(TRUE, TRUE, FALSE)
numeric <- c(1, 2, 3)
factor <- factor(c("low", "medium", "high"))
```



## Showing the data

```{r}
post_meal_data

glimpse(post_meal_data)
```


## Plot continous varibles

```{r}
#| fig-cap: "Distribution of BMI"
#| label: fig-bmi-histo
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram(na.rm = FALSE)
```


Af @fig-bmi-histo fremgår det, at ...

